# Generated by Django 3.1.3 on 2020-11-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='xCoord',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='yCoord',
            new_name='y',
        ),
    ]
